// Code generated by Prisma (prisma@1.23.2). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

import { DocumentNode } from "graphql";
import {
  makePrismaClientClass,
  BaseClientOptions,
  Model
} from "prisma-client-lib";
import { typeDefs } from "./prisma-schema";

export type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U];

export interface Exists {
  board: (where?: BoardWhereInput) => Promise<boolean>;
  column: (where?: ColumnWhereInput) => Promise<boolean>;
  user: (where?: UserWhereInput) => Promise<boolean>;
}

export interface Node {}

export type FragmentableArray<T> = Promise<Array<T>> & Fragmentable;

export interface Fragmentable {
  $fragment<T>(fragment: string | DocumentNode): Promise<T>;
}

export interface Prisma {
  $exists: Exists;
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>;

  /**
   * Queries
   */

  board: (where: BoardWhereUniqueInput) => BoardPromise;
  boards: (
    args?: {
      where?: BoardWhereInput;
      orderBy?: BoardOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<Board>;
  boardsConnection: (
    args?: {
      where?: BoardWhereInput;
      orderBy?: BoardOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => BoardConnectionPromise;
  column: (where: ColumnWhereUniqueInput) => ColumnPromise;
  columns: (
    args?: {
      where?: ColumnWhereInput;
      orderBy?: ColumnOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<Column>;
  columnsConnection: (
    args?: {
      where?: ColumnWhereInput;
      orderBy?: ColumnOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => ColumnConnectionPromise;
  user: (where: UserWhereUniqueInput) => UserPromise;
  users: (
    args?: {
      where?: UserWhereInput;
      orderBy?: UserOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<User>;
  usersConnection: (
    args?: {
      where?: UserWhereInput;
      orderBy?: UserOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => UserConnectionPromise;
  node: (args: { id: ID_Output }) => Node;

  /**
   * Mutations
   */

  createBoard: (data: BoardCreateInput) => BoardPromise;
  updateBoard: (
    args: { data: BoardUpdateInput; where: BoardWhereUniqueInput }
  ) => BoardPromise;
  updateManyBoards: (
    args: { data: BoardUpdateManyMutationInput; where?: BoardWhereInput }
  ) => BatchPayloadPromise;
  upsertBoard: (
    args: {
      where: BoardWhereUniqueInput;
      create: BoardCreateInput;
      update: BoardUpdateInput;
    }
  ) => BoardPromise;
  deleteBoard: (where: BoardWhereUniqueInput) => BoardPromise;
  deleteManyBoards: (where?: BoardWhereInput) => BatchPayloadPromise;
  createColumn: (data: ColumnCreateInput) => ColumnPromise;
  updateColumn: (
    args: { data: ColumnUpdateInput; where: ColumnWhereUniqueInput }
  ) => ColumnPromise;
  updateManyColumns: (
    args: { data: ColumnUpdateManyMutationInput; where?: ColumnWhereInput }
  ) => BatchPayloadPromise;
  upsertColumn: (
    args: {
      where: ColumnWhereUniqueInput;
      create: ColumnCreateInput;
      update: ColumnUpdateInput;
    }
  ) => ColumnPromise;
  deleteColumn: (where: ColumnWhereUniqueInput) => ColumnPromise;
  deleteManyColumns: (where?: ColumnWhereInput) => BatchPayloadPromise;
  createUser: (data: UserCreateInput) => UserPromise;
  updateUser: (
    args: { data: UserUpdateInput; where: UserWhereUniqueInput }
  ) => UserPromise;
  updateManyUsers: (
    args: { data: UserUpdateManyMutationInput; where?: UserWhereInput }
  ) => BatchPayloadPromise;
  upsertUser: (
    args: {
      where: UserWhereUniqueInput;
      create: UserCreateInput;
      update: UserUpdateInput;
    }
  ) => UserPromise;
  deleteUser: (where: UserWhereUniqueInput) => UserPromise;
  deleteManyUsers: (where?: UserWhereInput) => BatchPayloadPromise;

  /**
   * Subscriptions
   */

  $subscribe: Subscription;
}

export interface Subscription {
  board: (
    where?: BoardSubscriptionWhereInput
  ) => BoardSubscriptionPayloadSubscription;
  column: (
    where?: ColumnSubscriptionWhereInput
  ) => ColumnSubscriptionPayloadSubscription;
  user: (
    where?: UserSubscriptionWhereInput
  ) => UserSubscriptionPayloadSubscription;
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T;
}

/**
 * Types
 */

export type ColumnOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC"
  | "index_ASC"
  | "index_DESC"
  | "name_ASC"
  | "name_DESC"
  | "query_ASC"
  | "query_DESC";

export type BoardOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC"
  | "name_ASC"
  | "name_DESC"
  | "query_ASC"
  | "query_DESC";

export type UserOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC"
  | "name_ASC"
  | "name_DESC";

export type MutationType = "CREATED" | "UPDATED" | "DELETED";

export interface BoardUpdateInput {
  name?: String;
  query?: String;
  columns?: ColumnUpdateManyWithoutBoardInput;
}

export type BoardWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export interface ColumnUpdateWithoutBoardDataInput {
  index?: Int;
  name?: String;
  query?: String;
}

export interface BoardWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  updatedAt?: DateTimeInput;
  updatedAt_not?: DateTimeInput;
  updatedAt_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_lt?: DateTimeInput;
  updatedAt_lte?: DateTimeInput;
  updatedAt_gt?: DateTimeInput;
  updatedAt_gte?: DateTimeInput;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  query?: String;
  query_not?: String;
  query_in?: String[] | String;
  query_not_in?: String[] | String;
  query_lt?: String;
  query_lte?: String;
  query_gt?: String;
  query_gte?: String;
  query_contains?: String;
  query_not_contains?: String;
  query_starts_with?: String;
  query_not_starts_with?: String;
  query_ends_with?: String;
  query_not_ends_with?: String;
  columns_every?: ColumnWhereInput;
  columns_some?: ColumnWhereInput;
  columns_none?: ColumnWhereInput;
  AND?: BoardWhereInput[] | BoardWhereInput;
  OR?: BoardWhereInput[] | BoardWhereInput;
  NOT?: BoardWhereInput[] | BoardWhereInput;
}

export interface ColumnUpsertWithWhereUniqueWithoutBoardInput {
  where: ColumnWhereUniqueInput;
  update: ColumnUpdateWithoutBoardDataInput;
  create: ColumnCreateWithoutBoardInput;
}

export interface ColumnWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  updatedAt?: DateTimeInput;
  updatedAt_not?: DateTimeInput;
  updatedAt_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_lt?: DateTimeInput;
  updatedAt_lte?: DateTimeInput;
  updatedAt_gt?: DateTimeInput;
  updatedAt_gte?: DateTimeInput;
  board?: BoardWhereInput;
  index?: Int;
  index_not?: Int;
  index_in?: Int[] | Int;
  index_not_in?: Int[] | Int;
  index_lt?: Int;
  index_lte?: Int;
  index_gt?: Int;
  index_gte?: Int;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  query?: String;
  query_not?: String;
  query_in?: String[] | String;
  query_not_in?: String[] | String;
  query_lt?: String;
  query_lte?: String;
  query_gt?: String;
  query_gte?: String;
  query_contains?: String;
  query_not_contains?: String;
  query_starts_with?: String;
  query_not_starts_with?: String;
  query_ends_with?: String;
  query_not_ends_with?: String;
  AND?: ColumnWhereInput[] | ColumnWhereInput;
  OR?: ColumnWhereInput[] | ColumnWhereInput;
  NOT?: ColumnWhereInput[] | ColumnWhereInput;
}

export interface BoardUpdateOneRequiredWithoutColumnsInput {
  create?: BoardCreateWithoutColumnsInput;
  update?: BoardUpdateWithoutColumnsDataInput;
  upsert?: BoardUpsertWithoutColumnsInput;
  connect?: BoardWhereUniqueInput;
}

export interface ColumnUpdateManyWithWhereNestedInput {
  where: ColumnScalarWhereInput;
  data: ColumnUpdateManyDataInput;
}

export interface ColumnUpdateInput {
  board?: BoardUpdateOneRequiredWithoutColumnsInput;
  index?: Int;
  name?: String;
  query?: String;
}

export interface ColumnScalarWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  updatedAt?: DateTimeInput;
  updatedAt_not?: DateTimeInput;
  updatedAt_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_lt?: DateTimeInput;
  updatedAt_lte?: DateTimeInput;
  updatedAt_gt?: DateTimeInput;
  updatedAt_gte?: DateTimeInput;
  index?: Int;
  index_not?: Int;
  index_in?: Int[] | Int;
  index_not_in?: Int[] | Int;
  index_lt?: Int;
  index_lte?: Int;
  index_gt?: Int;
  index_gte?: Int;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  query?: String;
  query_not?: String;
  query_in?: String[] | String;
  query_not_in?: String[] | String;
  query_lt?: String;
  query_lte?: String;
  query_gt?: String;
  query_gte?: String;
  query_contains?: String;
  query_not_contains?: String;
  query_starts_with?: String;
  query_not_starts_with?: String;
  query_ends_with?: String;
  query_not_ends_with?: String;
  AND?: ColumnScalarWhereInput[] | ColumnScalarWhereInput;
  OR?: ColumnScalarWhereInput[] | ColumnScalarWhereInput;
  NOT?: ColumnScalarWhereInput[] | ColumnScalarWhereInput;
}

export interface BoardCreateWithoutColumnsInput {
  name?: String;
  query?: String;
}

export interface ColumnSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: ColumnWhereInput;
  AND?: ColumnSubscriptionWhereInput[] | ColumnSubscriptionWhereInput;
  OR?: ColumnSubscriptionWhereInput[] | ColumnSubscriptionWhereInput;
  NOT?: ColumnSubscriptionWhereInput[] | ColumnSubscriptionWhereInput;
}

export interface UserUpdateManyMutationInput {
  name?: String;
}

export interface UserUpdateInput {
  name?: String;
}

export interface BoardCreateInput {
  name?: String;
  query?: String;
  columns?: ColumnCreateManyWithoutBoardInput;
}

export interface ColumnUpdateManyMutationInput {
  index?: Int;
  name?: String;
  query?: String;
}

export interface ColumnCreateManyWithoutBoardInput {
  create?: ColumnCreateWithoutBoardInput[] | ColumnCreateWithoutBoardInput;
  connect?: ColumnWhereUniqueInput[] | ColumnWhereUniqueInput;
}

export interface BoardUpsertWithoutColumnsInput {
  update: BoardUpdateWithoutColumnsDataInput;
  create: BoardCreateWithoutColumnsInput;
}

export interface ColumnCreateWithoutBoardInput {
  index: Int;
  name?: String;
  query?: String;
}

export interface BoardUpdateWithoutColumnsDataInput {
  name?: String;
  query?: String;
}

export interface BoardCreateOneWithoutColumnsInput {
  create?: BoardCreateWithoutColumnsInput;
  connect?: BoardWhereUniqueInput;
}

export interface BoardSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: BoardWhereInput;
  AND?: BoardSubscriptionWhereInput[] | BoardSubscriptionWhereInput;
  OR?: BoardSubscriptionWhereInput[] | BoardSubscriptionWhereInput;
  NOT?: BoardSubscriptionWhereInput[] | BoardSubscriptionWhereInput;
}

export interface ColumnUpdateManyWithoutBoardInput {
  create?: ColumnCreateWithoutBoardInput[] | ColumnCreateWithoutBoardInput;
  delete?: ColumnWhereUniqueInput[] | ColumnWhereUniqueInput;
  connect?: ColumnWhereUniqueInput[] | ColumnWhereUniqueInput;
  disconnect?: ColumnWhereUniqueInput[] | ColumnWhereUniqueInput;
  update?:
    | ColumnUpdateWithWhereUniqueWithoutBoardInput[]
    | ColumnUpdateWithWhereUniqueWithoutBoardInput;
  upsert?:
    | ColumnUpsertWithWhereUniqueWithoutBoardInput[]
    | ColumnUpsertWithWhereUniqueWithoutBoardInput;
  deleteMany?: ColumnScalarWhereInput[] | ColumnScalarWhereInput;
  updateMany?:
    | ColumnUpdateManyWithWhereNestedInput[]
    | ColumnUpdateManyWithWhereNestedInput;
}

export interface UserCreateInput {
  name: String;
}

export interface ColumnUpdateManyDataInput {
  index?: Int;
  name?: String;
  query?: String;
}

export interface BoardUpdateManyMutationInput {
  name?: String;
  query?: String;
}

export interface ColumnCreateInput {
  board: BoardCreateOneWithoutColumnsInput;
  index: Int;
  name?: String;
  query?: String;
}

export interface ColumnUpdateWithWhereUniqueWithoutBoardInput {
  where: ColumnWhereUniqueInput;
  data: ColumnUpdateWithoutBoardDataInput;
}

export type UserWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export type ColumnWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export interface UserSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: UserWhereInput;
  AND?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
  OR?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
  NOT?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
}

export interface UserWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  updatedAt?: DateTimeInput;
  updatedAt_not?: DateTimeInput;
  updatedAt_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_lt?: DateTimeInput;
  updatedAt_lte?: DateTimeInput;
  updatedAt_gt?: DateTimeInput;
  updatedAt_gte?: DateTimeInput;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  AND?: UserWhereInput[] | UserWhereInput;
  OR?: UserWhereInput[] | UserWhereInput;
  NOT?: UserWhereInput[] | UserWhereInput;
}

export interface NodeNode {
  id: ID_Output;
}

export interface UserPreviousValues {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  name: String;
}

export interface UserPreviousValuesPromise
  extends Promise<UserPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  name: () => Promise<String>;
}

export interface UserPreviousValuesSubscription
  extends Promise<AsyncIterator<UserPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  name: () => Promise<AsyncIterator<String>>;
}

export interface ColumnEdge {
  node: Column;
  cursor: String;
}

export interface ColumnEdgePromise extends Promise<ColumnEdge>, Fragmentable {
  node: <T = ColumnPromise>() => T;
  cursor: () => Promise<String>;
}

export interface ColumnEdgeSubscription
  extends Promise<AsyncIterator<ColumnEdge>>,
    Fragmentable {
  node: <T = ColumnSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface BoardConnection {
  pageInfo: PageInfo;
  edges: BoardEdge[];
}

export interface BoardConnectionPromise
  extends Promise<BoardConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<BoardEdge>>() => T;
  aggregate: <T = AggregateBoardPromise>() => T;
}

export interface BoardConnectionSubscription
  extends Promise<AsyncIterator<BoardConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<BoardEdgeSubscription>>>() => T;
  aggregate: <T = AggregateBoardSubscription>() => T;
}

export interface ColumnConnection {
  pageInfo: PageInfo;
  edges: ColumnEdge[];
}

export interface ColumnConnectionPromise
  extends Promise<ColumnConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<ColumnEdge>>() => T;
  aggregate: <T = AggregateColumnPromise>() => T;
}

export interface ColumnConnectionSubscription
  extends Promise<AsyncIterator<ColumnConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<ColumnEdgeSubscription>>>() => T;
  aggregate: <T = AggregateColumnSubscription>() => T;
}

export interface BatchPayload {
  count: Long;
}

export interface BatchPayloadPromise
  extends Promise<BatchPayload>,
    Fragmentable {
  count: () => Promise<Long>;
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayload>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>;
}

export interface Column {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  index: Int;
  name?: String;
  query?: String;
}

export interface ColumnPromise extends Promise<Column>, Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  board: <T = BoardPromise>() => T;
  index: () => Promise<Int>;
  name: () => Promise<String>;
  query: () => Promise<String>;
}

export interface ColumnSubscription
  extends Promise<AsyncIterator<Column>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  board: <T = BoardSubscription>() => T;
  index: () => Promise<AsyncIterator<Int>>;
  name: () => Promise<AsyncIterator<String>>;
  query: () => Promise<AsyncIterator<String>>;
}

export interface ColumnSubscriptionPayload {
  mutation: MutationType;
  node: Column;
  updatedFields: String[];
  previousValues: ColumnPreviousValues;
}

export interface ColumnSubscriptionPayloadPromise
  extends Promise<ColumnSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = ColumnPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = ColumnPreviousValuesPromise>() => T;
}

export interface ColumnSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<ColumnSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = ColumnSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = ColumnPreviousValuesSubscription>() => T;
}

export interface PageInfo {
  hasNextPage: Boolean;
  hasPreviousPage: Boolean;
  startCursor?: String;
  endCursor?: String;
}

export interface PageInfoPromise extends Promise<PageInfo>, Fragmentable {
  hasNextPage: () => Promise<Boolean>;
  hasPreviousPage: () => Promise<Boolean>;
  startCursor: () => Promise<String>;
  endCursor: () => Promise<String>;
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfo>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>;
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>;
  startCursor: () => Promise<AsyncIterator<String>>;
  endCursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateBoard {
  count: Int;
}

export interface AggregateBoardPromise
  extends Promise<AggregateBoard>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateBoardSubscription
  extends Promise<AsyncIterator<AggregateBoard>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface ColumnPreviousValues {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  index: Int;
  name?: String;
  query?: String;
}

export interface ColumnPreviousValuesPromise
  extends Promise<ColumnPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  index: () => Promise<Int>;
  name: () => Promise<String>;
  query: () => Promise<String>;
}

export interface ColumnPreviousValuesSubscription
  extends Promise<AsyncIterator<ColumnPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  index: () => Promise<AsyncIterator<Int>>;
  name: () => Promise<AsyncIterator<String>>;
  query: () => Promise<AsyncIterator<String>>;
}

export interface UserEdge {
  node: User;
  cursor: String;
}

export interface UserEdgePromise extends Promise<UserEdge>, Fragmentable {
  node: <T = UserPromise>() => T;
  cursor: () => Promise<String>;
}

export interface UserEdgeSubscription
  extends Promise<AsyncIterator<UserEdge>>,
    Fragmentable {
  node: <T = UserSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface UserSubscriptionPayload {
  mutation: MutationType;
  node: User;
  updatedFields: String[];
  previousValues: UserPreviousValues;
}

export interface UserSubscriptionPayloadPromise
  extends Promise<UserSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = UserPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = UserPreviousValuesPromise>() => T;
}

export interface UserSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<UserSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = UserSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = UserPreviousValuesSubscription>() => T;
}

export interface BoardPreviousValues {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  name?: String;
  query?: String;
}

export interface BoardPreviousValuesPromise
  extends Promise<BoardPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  name: () => Promise<String>;
  query: () => Promise<String>;
}

export interface BoardPreviousValuesSubscription
  extends Promise<AsyncIterator<BoardPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  name: () => Promise<AsyncIterator<String>>;
  query: () => Promise<AsyncIterator<String>>;
}

export interface BoardSubscriptionPayload {
  mutation: MutationType;
  node: Board;
  updatedFields: String[];
  previousValues: BoardPreviousValues;
}

export interface BoardSubscriptionPayloadPromise
  extends Promise<BoardSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = BoardPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = BoardPreviousValuesPromise>() => T;
}

export interface BoardSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<BoardSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = BoardSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = BoardPreviousValuesSubscription>() => T;
}

export interface Board {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  name?: String;
  query?: String;
}

export interface BoardPromise extends Promise<Board>, Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  name: () => Promise<String>;
  query: () => Promise<String>;
  columns: <T = FragmentableArray<Column>>(
    args?: {
      where?: ColumnWhereInput;
      orderBy?: ColumnOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface BoardSubscription
  extends Promise<AsyncIterator<Board>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  name: () => Promise<AsyncIterator<String>>;
  query: () => Promise<AsyncIterator<String>>;
  columns: <T = Promise<AsyncIterator<ColumnSubscription>>>(
    args?: {
      where?: ColumnWhereInput;
      orderBy?: ColumnOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface BoardEdge {
  node: Board;
  cursor: String;
}

export interface BoardEdgePromise extends Promise<BoardEdge>, Fragmentable {
  node: <T = BoardPromise>() => T;
  cursor: () => Promise<String>;
}

export interface BoardEdgeSubscription
  extends Promise<AsyncIterator<BoardEdge>>,
    Fragmentable {
  node: <T = BoardSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface User {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  name: String;
}

export interface UserPromise extends Promise<User>, Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  name: () => Promise<String>;
}

export interface UserSubscription
  extends Promise<AsyncIterator<User>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  name: () => Promise<AsyncIterator<String>>;
}

export interface UserConnection {
  pageInfo: PageInfo;
  edges: UserEdge[];
}

export interface UserConnectionPromise
  extends Promise<UserConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<UserEdge>>() => T;
  aggregate: <T = AggregateUserPromise>() => T;
}

export interface UserConnectionSubscription
  extends Promise<AsyncIterator<UserConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<UserEdgeSubscription>>>() => T;
  aggregate: <T = AggregateUserSubscription>() => T;
}

export interface AggregateUser {
  count: Int;
}

export interface AggregateUserPromise
  extends Promise<AggregateUser>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateUserSubscription
  extends Promise<AsyncIterator<AggregateUser>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface AggregateColumn {
  count: Int;
}

export interface AggregateColumnPromise
  extends Promise<AggregateColumn>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateColumnSubscription
  extends Promise<AsyncIterator<AggregateColumn>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string;

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. 
*/
export type Int = number;

/*
DateTime scalar input type, allowing Date
*/
export type DateTimeInput = Date | string;

/*
DateTime scalar output type, which is always a string
*/
export type DateTimeOutput = string;

export type Long = string;

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number;
export type ID_Output = string;

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean;

/**
 * Model Metadata
 */

export const models: Model[] = [
  {
    name: "Board",
    embedded: false
  },
  {
    name: "Column",
    embedded: false
  },
  {
    name: "User",
    embedded: false
  }
];

/**
 * Type Defs
 */

export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  models,
  endpoint: `https://us1.prisma.sh/cole-bemis-8ac4aa/dasher/dev`
});
export const prisma = new Prisma();
